# Site settings
title:       Blog & Projects
email:       tristan.ruml@gmail.com
author:      Tristan Ruml
description: "Random observations and projects I've worked on."

# I commented out this line for now
#baseurl:    "tkruml.github.io"
url:         "//tkruml.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: tkruml
twitter_username:
google_plus_id: tristanruml
linkedin_username: tristanruml
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
