# Site settings
title:       Tristan Ruml | Portfolio
email:       tristan.ruml@gmail.com
author:      Tristan Ruml
description: "My portfolio and blog website."

# I commented out this line for now
#baseurl:    "tkruml.github.io"
url:         "/tkruml.github.io"

# Google analytics
google_analytics: UA-47107509-1

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: tkruml
twitter_username:
google_plus_id: +TristanRuml
linkedin_username: tristanruml
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
